### PR TITLE
Add new dates for 2019-2020

### PR DESCRIPTION
**Pull request by Coteh**
Not 100% sure if these term end dates will properly fix the sequencing issue for repeat events but FWIW I tested the F19 end date using my own schedule and my complete schedule seems to be exported ~with no issue (no missing events and no extra events).~ edit: I'm wrong (sorry, it's a late night 😅) looks like there's an exam, three lectures, and two labs missing after setting end date to Dec. 2, 4, and 9. I will have to take another look later.

### CODE REVIEW

**Comment by Fogest** [comment]
You need to use the dates found on the important dates schedules: https://www.uoguelph.ca/registrar/calendars/undergraduate/current/c03/index.shtml

You'll see in the Fall 2019 one for example that it states a date for when exams conclude. So you can just put in an end date that is the day after that date listed :)

**Comment by Coteh** [comment]
Ah I see. I was taking a look at this as well as the [2018-2019 version](https://www.uoguelph.ca/registrar/calendars/undergraduate/2018-2019/c03/index.shtml) to compare and it seemed a bit inconsistent to me. E.g. F18 `termEnd` is Dec. 5, but the examination conclude is Dec. 14, and for S18 `termEnd` is Sep. 1 but the examination conclude is Aug. 17.

I can update the term ends I added in this PR to be a day after the exam conclusion dates. Thanks for the help!

**Comment by Fogest** [comment]
Ah yes, my mistake you're right. The termEnd actually represents the day following the last day of classes as this is used to determine when to end the repeating calendar entries. The exams are set based on exact dates/times so no termEnd date is needed as they are not repeating.

**Comment by Fogest** [comment]
@Coteh So based on what  I was talking about and the mistake I made, is this pull correct, or did you need to make a change still?

**Comment by Coteh** [comment]
Oh sorry, this one’s not completely ready yet. Was going to do more experimenting but haven’t gotten around to it yet. I’ll let you know when I update this PR.

On Sep 3, 2019, at 3:38 PM, Justin <notifications@github.com<mailto:notifications@github.com>> wrote:


@Coteh<https://github.com/Coteh> So based on what I was talking about and the mistake I made, is this pull correct, or did you need to make a change still?

**Comment by Coteh** [comment]
@Fogest Ready for review

**Review by Fogest — APPROVED** [review]

**Comment by Fogest** [comment]
Merged and pulled it on the production site. Thanks ❤️

**Pull request merged**
